# Generated by Django 3.2.7 on 2021-10-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_spec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_shef',
        ),
    ]
