# Generated by Django 3.2.7 on 2021-10-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menu_maki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_kalif_kunj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Калифорния кунжут',
                'verbose_name_plural': 'Калифорния кунжут',
            },
        ),
        migrations.AlterModelOptions(
            name='menu_maki',
            options={'verbose_name': 'Маки', 'verbose_name_plural': 'Маки'},
        ),
        migrations.AlterModelOptions(
            name='menu_shef',
            options={'verbose_name': 'Ролы от шефа', 'verbose_name_plural': 'Ролы от шефа'},
        ),
        migrations.AlterField(
            model_name='menu_maki',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menu_maki',
            name='spec',
            field=models.CharField(blank=True, max_length=100, verbose_name='Состав'),
        ),
    ]
