# Generated by Django 3.2.7 on 2021-10-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211006_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_kalif_tobiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Калифорния тобико',
                'verbose_name_plural': 'Калифорния тобико',
            },
        ),
    ]
