# Generated by Django 3.2.7 on 2021-10-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menu_kalif_tobiko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сыр филадельфия',
                'verbose_name_plural': 'Сыр филадельфия',
            },
        ),
        migrations.AlterField(
            model_name='menu_kalif_kunj',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menu_kalif_tobiko',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menu_maki',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
