# Generated by Django 3.2.7 on 2021-10-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menu_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_nigiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Суши нигири',
                'verbose_name_plural': 'Суши нигири',
            },
        ),
        migrations.AlterModelOptions(
            name='menu_sets',
            options={'verbose_name': 'Сеты', 'verbose_name_plural': 'Сет'},
        ),
        migrations.AlterField(
            model_name='menu_sets',
            name='spec',
            field=models.CharField(blank=True, max_length=200, verbose_name='Состав'),
        ),
    ]
