# Generated by Django 3.2.7 on 2021-10-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211007_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_pub_alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Алкоголь',
                'verbose_name_plural': 'Алкоголь',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_coctail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Коктели',
                'verbose_name_plural': 'Коктель',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_coctail_non',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Безалкогольные коктели',
                'verbose_name_plural': 'Безалкогольный коктель',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Десерты',
                'verbose_name_plural': 'Десерт',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_garnish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Гарниры',
                'verbose_name_plural': 'Гарнир',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_grill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Гриль блюда',
                'verbose_name_plural': 'Гриль блюдо',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Домашние блюда',
                'verbose_name_plural': 'Домашнее блюдо',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ланчи',
                'verbose_name_plural': 'Ланч',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пицца',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_soup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Супы',
                'verbose_name_plural': 'Суп',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Чай/кофе',
                'verbose_name_plural': 'Чай/кофе',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вода',
                'verbose_name_plural': 'Вода',
            },
        ),
    ]
