# Generated by Django 3.2.7 on 2021-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_menu_pub_alcohol_menu_pub_coctail_menu_pub_coctail_non_menu_pub_dessert_menu_pub_garnish_menu_pub_gr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_pub_salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Салаты',
                'verbose_name_plural': 'Салат',
            },
        ),
    ]
