# Generated by Django 3.2.7 on 2021-10-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_menu_pub_fish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_pub_alcohol',
            new_name='Menu_pub_vodka',
        ),
        migrations.AlterModelOptions(
            name='menu_pub_vodka',
            options={'verbose_name': 'Vodka', 'verbose_name_plural': 'Vodka'},
        ),
        migrations.AlterField(
            model_name='menu_pub_grill',
            name='weight',
            field=models.CharField(max_length=20, verbose_name='Вес'),
        ),
    ]
