# Generated by Django 3.2.7 on 2021-10-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alco_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_alco_vodka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Vodka',
                'verbose_name_plural': 'Vodka',
            },
        ),
        migrations.RenameModel(
            old_name='Menu_pub_brendi',
            new_name='Menu_alco_brendi',
        ),
        migrations.DeleteModel(
            name='Menu_pub_vodka',
        ),
    ]
