# Generated by Django 3.2.7 on 2021-10-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211018_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_alco_beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beer',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_djin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Djin',
                'verbose_name_plural': 'Djin',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_konjack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Konjack',
                'verbose_name_plural': 'Konjack',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_liker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Liker',
                'verbose_name_plural': 'Liker',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Rom',
                'verbose_name_plural': 'Rom',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_tekila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Tekila',
                'verbose_name_plural': 'Tekila',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_Vermut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Vermut',
                'verbose_name_plural': 'Vermut',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_vine_bokal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Vine bokal',
                'verbose_name_plural': 'Vine bokal',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_vine_igr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Vine igr',
                'verbose_name_plural': 'Vine igr',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_vine_red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Vine red',
                'verbose_name_plural': 'Vine red',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_vine_white',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Vine white',
                'verbose_name_plural': 'Vine white',
            },
        ),
        migrations.CreateModel(
            name='Menu_alco_whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Whiskey',
                'verbose_name_plural': 'Whiskey',
            },
        ),
        migrations.DeleteModel(
            name='alco_menu',
        ),
    ]
