# Generated by Django 3.2.7 on 2021-10-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_some'),
    ]

    operations = [
        migrations.DeleteModel(
            name='some',
        ),
        migrations.AddField(
            model_name='menu_shef',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
