# Generated by Django 3.2.7 on 2021-10-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211027_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_shef',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
    ]
