# Generated by Django 3.2.7 on 2021-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_menu_shef_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_shef',
            name='image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
