# Generated by Django 3.2.8 on 2021-10-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_menu_shef_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_maki',
            name='image',
            field=models.ImageField(default='/media/sushi/empty.png', upload_to='sushi'),
        ),
    ]
