# Generated by Django 3.2.8 on 2021-10-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_menu_maki_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_maki',
            name='image',
            field=models.ImageField(default='sushi/empty.png', upload_to='sushi'),
        ),
    ]
