# Generated by Django 3.2.8 on 2021-10-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_menu_maki_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_kalif_kunj',
            name='image',
            field=models.ImageField(default='sushi/empty.png', upload_to='sushi'),
        ),
    ]
