# Generated by Django 3.2.8 on 2021-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211028_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_cheese',
            name='image',
            field=models.ImageField(default='sushi/empty.png', upload_to='sushi'),
        ),
    ]
