# Generated by Django 3.2.7 on 2021-10-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_menu_cheese_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_alco_beer',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_brendi',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_djin',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_konjack',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_liker',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_rom',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_tekila',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_vermut',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_vine_bokal',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_vine_igr',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_vine_red',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_vine_white',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_vodka',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_alco_whiskey',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_coctail',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_coctail_non',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_dessert',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_fish',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_garnish',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_grill',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_home',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_lunch',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_pizza',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_salad',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_soup',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_tea',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
        migrations.AddField(
            model_name='menu_pub_water',
            name='image',
            field=models.ImageField(default='pub/empty.png', upload_to='pub'),
        ),
    ]
