# Generated by Django 3.2.7 on 2021-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20211029_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub_news',
            name='spec',
            field=models.TextField(blank=True, max_length=300, verbose_name='Новость'),
        ),
    ]
