# Generated by Django 3.2.7 on 2021-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_pub_news_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_pub_zak_beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('image', models.ImageField(default='pub/empty.png', upload_to='pub')),
            ],
            options={
                'verbose_name': 'Закуски к пиву',
                'verbose_name_plural': 'Закуска к пиву',
            },
        ),
        migrations.CreateModel(
            name='Menu_pub_zak_cold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('image', models.ImageField(default='pub/empty.png', upload_to='pub')),
            ],
            options={
                'verbose_name': 'Холодные закуски',
                'verbose_name_plural': 'Холодная закуска',
            },
        ),
    ]
