# Generated by Django 3.2.7 on 2021-11-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_menu_pub_zak_beer_menu_pub_zak_cold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_pub_zak_beer',
            options={'verbose_name': 'Закуска к пиву', 'verbose_name_plural': 'Закуски к пиву'},
        ),
        migrations.AlterModelOptions(
            name='menu_pub_zak_cold',
            options={'verbose_name': 'Закуски холодные', 'verbose_name_plural': 'Холодная закуска'},
        ),
    ]
